name: ${pluginDescription.name}
description: ${project.description}
authors: [${pluginDescription.authors}]
website: ${project.url}
main: ${pluginDescription.main}
version: ${pluginDescription.version}
api-version: 1.16
depend: [ C20Core ]