# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      continue-on-error: true
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: target/WayPortals-*.jar
        tag: ${{ github.ref }}
